import "./globals.css";
import { Mulish, Tenor_Sans } from "next/font/google";
import { Appwrapper } from "./Context";
import Message from "./_globalcomps/Message";
import { Googleadsid } from "@/lib/data";

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
  display: "swap",
});

const tenor = Tenor_Sans({
  variable: "--font-tenor",
  weight: "400", // Tenor Sans has only one weight
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* google adsense */}
        <script
          async
          src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${Googleadsid}`}
          crossOrigin="anonymous"
        ></script>
        <meta name="google-adsense-account" content={Googleadsid} />
      </head>
      {/* ✅ Mulish applied globally, Tenor available via class */}
      <body
        className={`${mulish.variable} ${tenor.variable} antialiased max-w-[1900px] mx-auto text-[#525252]`}
      >
        <Appwrapper>
          {children}
          <Message />
        </Appwrapper>
      </body>
    </html>
  );
}
