import {
  FaFacebook,
  FaTwitter,
  FaInstagram,
  FaLinkedin,
  FaGithub,
  FaYoutube,
  FaPinterest,
  FaReddit,
  FaTiktok,
  FaSnapchat,
  FaWhatsapp,
  FaTelegram,
  FaDiscord,
  FaTwitch,
} from "react-icons/fa";

export const logintime = [60 * 60 * 24 * 30, "30d"]; // 30 days

export const CACHE_TIME = 60 * 60 * 24 * 7; //7days

// google ads id
export const Googleadsid = "ca-pub-7398670337880164";

// store categories
export const prestorescollections = {
  Furniture: [
    {
      name: "Living Room",
      image: "",
      subcat: [
        { name: "Sofa Sets", image: "" },
        { name: "Chairs", image: "" },
        { name: "Sofa Cum Bed", image: "" },
        { name: "Wing Chairs", image: "" },
        { name: "Ottoman", image: "" },
        { name: "Recliners", image: "" },
        { name: "TV Units", image: "" },
        { name: "Coffee Tables", image: "" },
      ],
    },
    {
      name: "Bedroom",
      image: "",
      subcat: [
        { name: "Beds", image: "" },
        { name: "Wardrobes", image: "" },
        { name: "Dressers", image: "" },
        { name: "Bedside Tables", image: "" },
        { name: "Mattresses", image: "" },
      ],
    },
    {
      name: "Dining Room",
      image: "",
      subcat: [
        { name: "Dining Sets", image: "" },
        { name: "Dining Chairs", image: "" },
        { name: "Dining Tables", image: "" },
        { name: "Crockery Units", image: "" },
      ],
    },
    {
      name: "Office Furniture",
      image: "",
      subcat: [
        { name: "Office Chairs", image: "" },
        { name: "Office Tables", image: "" },
        { name: "Cabin Furniture", image: "" },
        { name: "Reception Units", image: "" },
      ],
    },
    {
      name: "Outdoor Furniture",
      image: "",
      subcat: [
        { name: "Patio Sets", image: "" },
        { name: "Garden Chairs", image: "" },
        { name: "Outdoor Tables", image: "" },
        { name: "Swing Chairs", image: "" },
      ],
    },
    {
      name: "Storage",
      image: "",
      subcat: [
        { name: "Bookshelves", image: "" },
        { name: "Shoe Racks", image: "" },
        { name: "Cabinets", image: "" },
        { name: "Sideboards", image: "" },
      ],
    },
    {
      name: "Decor",
      image: "",
      subcat: [
        { name: "Wall Art", image: "" },
        { name: "Mirrors", image: "" },
        { name: "Lamps", image: "" },
        { name: "Rugs & Carpets", image: "" },
      ],
    },
    {
      name: "Kids Room",
      image: "",
      subcat: [
        { name: "Kids Beds", image: "" },
        { name: "Study Tables", image: "" },
        { name: "Toy Storage", image: "" },
        { name: "Kids Chairs", image: "" },
      ],
    },
  ],
  Shoes: [
    {
      name: "Men's Footwear",
      image: "",
      subcat: [
        { name: "Casual Shoes", image: "" },
        { name: "Formal Shoes", image: "" },
        { name: "Sneakers", image: "" },
        { name: "Sports Shoes", image: "" },
        { name: "Loafers", image: "" },
        { name: "Boots", image: "" },
        { name: "Sandals & Floaters", image: "" },
        { name: "Flip Flops", image: "" },
      ],
    },
    {
      name: "Women's Footwear",
      image: "",
      subcat: [
        { name: "Heels", image: "" },
        { name: "Flats", image: "" },
        { name: "Sneakers", image: "" },
        { name: "Ballerinas", image: "" },
        { name: "Sandals", image: "" },
        { name: "Boots", image: "" },
        { name: "Flip Flops", image: "" },
        { name: "Ethnic Footwear", image: "" },
      ],
    },
    {
      name: "Kids' Footwear",
      image: "",
      subcat: [
        { name: "Casual Shoes", image: "" },
        { name: "School Shoes", image: "" },
        { name: "Sports Shoes", image: "" },
        { name: "Sandals & Slippers", image: "" },
        { name: "Boots", image: "" },
      ],
    },
    {
      name: "Sports & Performance",
      image: "",
      subcat: [
        { name: "Running Shoes", image: "" },
        { name: "Training Shoes", image: "" },
        { name: "Football Shoes", image: "" },
        { name: "Cricket Shoes", image: "" },
        { name: "Hiking Boots", image: "" },
        { name: "Cycling Shoes", image: "" },
      ],
    },
    {
      name: "Shoes by Brand",
      image: "",
      subcat: [
        { name: "Nike", image: "" },
        { name: "Adidas", image: "" },
        { name: "Puma", image: "" },
        { name: "Reebok", image: "" },
        { name: "Skechers", image: "" },
        { name: "Bata", image: "" },
        { name: "Woodland", image: "" },
        { name: "Red Tape", image: "" },
      ],
    },
    {
      name: "Seasonal Collection",
      image: "",
      subcat: [
        { name: "Summer Collection", image: "" },
        { name: "Monsoon Collection", image: "" },
        { name: "Winter Boots", image: "" },
        { name: "Festive Wear", image: "" },
      ],
    },
    {
      name: "Accessories & Care",
      image: "",
      subcat: [
        { name: "Socks", image: "" },
        { name: "Shoe Polish & Brushes", image: "" },
        { name: "Insoles & Cushions", image: "" },
        { name: "Shoe Bags", image: "" },
        { name: "Laces", image: "" },
      ],
    },
  ],
  Electronics: [
    {
      name: "Mobiles & Tablets",
      image: "",
      subcat: [
        { name: "Smartphones", image: "" },
        { name: "Feature Phones", image: "" },
        { name: "Tablets", image: "" },
        { name: "Mobile Accessories", image: "" },
        { name: "Chargers & Cables", image: "" },
        { name: "Power Banks", image: "" },
        { name: "Smartwatches", image: "" },
      ],
    },
    {
      name: "Laptops & Computers",
      image: "",
      subcat: [
        { name: "Laptops", image: "" },
        { name: "Desktops", image: "" },
        { name: "Monitors", image: "" },
        { name: "Printers & Scanners", image: "" },
        { name: "Computer Accessories", image: "" },
        { name: "Storage Devices", image: "" },
        { name: "Networking Devices", image: "" },
      ],
    },
    {
      name: "Televisions",
      image: "",
      subcat: [
        { name: "Smart TVs", image: "" },
        { name: "LED TVs", image: "" },
        { name: "OLED TVs", image: "" },
        { name: "QLED TVs", image: "" },
        { name: "TV Accessories", image: "" },
      ],
    },
    {
      name: "Home Appliances",
      image: "",
      subcat: [
        { name: "Refrigerators", image: "" },
        { name: "Washing Machines", image: "" },
        { name: "Air Conditioners", image: "" },
        { name: "Microwave Ovens", image: "" },
        { name: "Water Purifiers", image: "" },
        { name: "Vacuum Cleaners", image: "" },
      ],
    },
    {
      name: "Audio",
      image: "",
      subcat: [
        { name: "Headphones & Earbuds", image: "" },
        { name: "Bluetooth Speakers", image: "" },
        { name: "Home Theatres", image: "" },
        { name: "Soundbars", image: "" },
      ],
    },
    {
      name: "Cameras & Accessories",
      image: "",
      subcat: [
        { name: "DSLR Cameras", image: "" },
        { name: "Mirrorless Cameras", image: "" },
        { name: "Action Cameras", image: "" },
        { name: "Camera Lenses", image: "" },
        { name: "Tripods & Mounts", image: "" },
      ],
    },
    {
      name: "Gaming",
      image: "",
      subcat: [
        { name: "Gaming Consoles", image: "" },
        { name: "Gaming Laptops", image: "" },
        { name: "Controllers", image: "" },
        { name: "VR Headsets", image: "" },
        { name: "Gaming Accessories", image: "" },
      ],
    },
    {
      name: "Wearable Tech",
      image: "",
      subcat: [
        { name: "Smartwatches", image: "" },
        { name: "Fitness Bands", image: "" },
        { name: "Smart Glasses", image: "" },
      ],
    },
    {
      name: "Kitchen Appliances",
      image: "",
      subcat: [
        { name: "Mixer Grinders", image: "" },
        { name: "Induction Cooktops", image: "" },
        { name: "Toasters & Sandwich Makers", image: "" },
        { name: "Coffee Machines", image: "" },
        { name: "Air Fryers", image: "" },
      ],
    },
  ],
  Laptops: [
    {
      name: "Laptops by Type",
      image: "",
      subcat: [
        { name: "Gaming Laptops", image: "" },
        { name: "Business Laptops", image: "" },
        { name: "Student Laptops", image: "" },
        { name: "2-in-1 Laptops", image: "" },
        { name: "Ultrabooks", image: "" },
        { name: "Budget Laptops", image: "" },
      ],
    },
    {
      name: "Laptops by Brand",
      image: "",
      subcat: [
        { name: "Apple", image: "" },
        { name: "Dell", image: "" },
        { name: "HP", image: "" },
        { name: "Lenovo", image: "" },
        { name: "Asus", image: "" },
        { name: "Acer", image: "" },
        { name: "MSI", image: "" },
        { name: "Samsung", image: "" },
      ],
    },
    {
      name: "Laptops by Screen Size",
      image: "",
      subcat: [
        { name: "Below 13 inch", image: "" },
        { name: "13 inch - 14 inch", image: "" },
        { name: "15 inch - 16 inch", image: "" },
        { name: "Above 16 inch", image: "" },
      ],
    },
    {
      name: "Laptops by Processor",
      image: "",
      subcat: [
        { name: "Intel Core i3", image: "" },
        { name: "Intel Core i5", image: "" },
        { name: "Intel Core i7", image: "" },
        { name: "Intel Core i9", image: "" },
        { name: "AMD Ryzen 3", image: "" },
        { name: "AMD Ryzen 5", image: "" },
        { name: "AMD Ryzen 7", image: "" },
        { name: "Apple M1/M2", image: "" },
      ],
    },
    {
      name: "Laptop Accessories",
      image: "",
      subcat: [
        { name: "Laptop Bags", image: "" },
        { name: "Cooling Pads", image: "" },
        { name: "Laptop Stands", image: "" },
        { name: "Docking Stations", image: "" },
        { name: "Chargers & Adapters", image: "" },
        { name: "External Keyboards", image: "" },
        { name: "External Mice", image: "" },
      ],
    },
    {
      name: "Software & Services",
      image: "",
      subcat: [
        { name: "Operating Systems", image: "" },
        { name: "Office Suites", image: "" },
        { name: "Antivirus Software", image: "" },
        { name: "Cloud Storage", image: "" },
        { name: "Extended Warranty", image: "" },
      ],
    },
  ],
  Mobiles: [
    {
      name: "Smartphones by Brand",
      image: "",
      subcat: [
        { name: "Apple iPhone", image: "" },
        { name: "Samsung", image: "" },
        { name: "OnePlus", image: "" },
        { name: "Xiaomi (Mi / Redmi)", image: "" },
        { name: "Realme", image: "" },
        { name: "Vivo", image: "" },
        { name: "Oppo", image: "" },
        { name: "Google Pixel", image: "" },
        { name: "Motorola", image: "" },
        { name: "Nothing", image: "" },
      ],
    },
    {
      name: "Smartphones by Price",
      image: "",
      subcat: [
        { name: "Under ₹10,000", image: "" },
        { name: "₹10,000 - ₹20,000", image: "" },
        { name: "₹20,000 - ₹30,000", image: "" },
        { name: "₹30,000 - ₹50,000", image: "" },
        { name: "Above ₹50,000", image: "" },
        { name: "Flagship Phones", image: "" },
      ],
    },
    {
      name: "Smartphones by Features",
      image: "",
      subcat: [
        { name: "5G Phones", image: "" },
        { name: "Gaming Phones", image: "" },
        { name: "Camera Phones", image: "" },
        { name: "Long Battery Life", image: "" },
        { name: "Fast Charging", image: "" },
        { name: "Foldable Phones", image: "" },
        { name: "Compact Phones", image: "" },
      ],
    },
    {
      name: "Mobile Accessories",
      image: "",
      subcat: [
        { name: "Cases & Covers", image: "" },
        { name: "Screen Protectors", image: "" },
        { name: "Chargers & Adapters", image: "" },
        { name: "Cables", image: "" },
        { name: "Power Banks", image: "" },
        { name: "Earphones & Headphones", image: "" },
        { name: "Bluetooth Speakers", image: "" },
        { name: "Smartwatches", image: "" },
      ],
    },
    {
      name: "Wearables & Connected Devices",
      image: "",
      subcat: [
        { name: "Smartwatches", image: "" },
        { name: "Fitness Bands", image: "" },
        { name: "VR Headsets", image: "" },
        { name: "Smart Glasses", image: "" },
      ],
    },
    {
      name: "Tablets & iPads",
      image: "",
      subcat: [
        { name: "Android Tablets", image: "" },
        { name: "iPads", image: "" },
        { name: "Kids Tablets", image: "" },
        { name: "Tablet Accessories", image: "" },
      ],
    },
    {
      name: "Mobile Services",
      image: "",
      subcat: [
        { name: "Mobile Insurance", image: "" },
        { name: "Extended Warranty", image: "" },
        { name: "Repair Services", image: "" },
        { name: "Buyback & Exchange", image: "" },
      ],
    },
  ],
  Clothes: [
    {
      name: "Men's Clothing",
      image: "",
      subcat: [
        { name: "T-Shirts", image: "" },
        { name: "Shirts", image: "" },
        { name: "Jeans", image: "" },
        { name: "Trousers", image: "" },
        { name: "Shorts", image: "" },
        { name: "Jackets", image: "" },
        { name: "Suits & Blazers", image: "" },
        { name: "Ethnic Wear", image: "" },
        { name: "Activewear", image: "" },
      ],
    },
    {
      name: "Women's Clothing",
      image: "",
      subcat: [
        { name: "Kurtas & Kurtis", image: "" },
        { name: "Tops & Tees", image: "" },
        { name: "Sarees", image: "" },
        { name: "Dresses", image: "" },
        { name: "Jeans & Jeggings", image: "" },
        { name: "Skirts", image: "" },
        { name: "Ethnic Sets", image: "" },
        { name: "Jackets & Shrugs", image: "" },
        { name: "Activewear", image: "" },
      ],
    },
    {
      name: "Kids' Clothing",
      image: "",
      subcat: [
        { name: "T-Shirts & Shirts", image: "" },
        { name: "Dresses & Frocks", image: "" },
        { name: "Shorts & Trousers", image: "" },
        { name: "Nightwear", image: "" },
        { name: "Ethnic Wear", image: "" },
        { name: "Winterwear", image: "" },
      ],
    },
    {
      name: "Winterwear",
      image: "",
      subcat: [
        { name: "Sweaters", image: "" },
        { name: "Hoodies", image: "" },
        { name: "Sweatshirts", image: "" },
        { name: "Jackets", image: "" },
        { name: "Thermals", image: "" },
      ],
    },
    {
      name: "Innerwear & Sleepwear",
      image: "",
      subcat: [
        { name: "Men’s Innerwear", image: "" },
        { name: "Women’s Lingerie", image: "" },
        { name: "Nightwear", image: "" },
        { name: "Socks", image: "" },
        { name: "Thermal Wear", image: "" },
      ],
    },
    {
      name: "Footwear & Accessories",
      image: "",
      subcat: [
        { name: "Casual Shoes", image: "" },
        { name: "Formal Shoes", image: "" },
        { name: "Sandals & Flip Flops", image: "" },
        { name: "Heels", image: "" },
        { name: "Sneakers", image: "" },
        { name: "Belts", image: "" },
        { name: "Caps & Hats", image: "" },
      ],
    },
    {
      name: "Ethnic & Traditional",
      image: "",
      subcat: [
        { name: "Men’s Kurta Sets", image: "" },
        { name: "Women’s Sarees", image: "" },
        { name: "Lehengas", image: "" },
        { name: "Sherwanis", image: "" },
        { name: "Dupattas & Stoles", image: "" },
      ],
    },
    {
      name: "Fashion Accessories",
      image: "",
      subcat: [
        { name: "Watches", image: "" },
        { name: "Sunglasses", image: "" },
        { name: "Bags & Wallets", image: "" },
        { name: "Jewellery", image: "" },
        { name: "Scarves & Stoles", image: "" },
      ],
    },
  ],
  Food: [
    {
      name: "Fruits & Vegetables",
      image: "",
      subcat: [
        { name: "Seasonal Fruits", image: "" },
        { name: "Leafy Vegetables", image: "" },
        { name: "Root Vegetables", image: "" },
        { name: "Tomatoes & Onions", image: "" },
        { name: "Organic Produce", image: "" },
      ],
    },
    {
      name: "Street Snacks",
      image: "",
      subcat: [
        { name: "Samosa & Kachori", image: "" },
        { name: "Pav Bhaji", image: "" },
        { name: "Vada Pav", image: "" },
        { name: "Chaat Items", image: "" },
        { name: "Pani Puri / Golgappa", image: "" },
        { name: "Pakoras & Fritters", image: "" },
      ],
    },
    {
      name: "Indian Sweets & Mithai",
      image: "",
      subcat: [
        { name: "Laddu & Barfi", image: "" },
        { name: "Jalebi & Imarti", image: "" },
        { name: "Rasgulla & Rasmalai", image: "" },
        { name: "Gulab Jamun", image: "" },
        { name: "Soan Papdi", image: "" },
      ],
    },
    {
      name: "Beverages & Refreshments",
      image: "",
      subcat: [
        { name: "Chai / Tea", image: "" },
        { name: "Coffee", image: "" },
        { name: "Lassi & Buttermilk", image: "" },
        { name: "Sugarcane Juice", image: "" },
        { name: "Cold Drinks", image: "" },
        { name: "Fresh Juices", image: "" },
      ],
    },
    {
      name: "Spices & Masalas",
      image: "",
      subcat: [
        { name: "Whole Spices", image: "" },
        { name: "Ground Masalas", image: "" },
        { name: "Pickles & Chutneys", image: "" },
        { name: "Ginger-Garlic Paste", image: "" },
        { name: "Tamarind & Dry Herbs", image: "" },
      ],
    },
    {
      name: "Staples & Grains",
      image: "",
      subcat: [
        { name: "Rice & Dals", image: "" },
        { name: "Atta / Flour", image: "" },
        { name: "Pulses", image: "" },
        { name: "Cooking Oils", image: "" },
        { name: "Salt & Sugar", image: "" },
      ],
    },
    {
      name: "Frozen & Packaged",
      image: "",
      subcat: [
        { name: "Frozen Snacks", image: "" },
        { name: "Ready-to-Cook Meals", image: "" },
        { name: "Frozen Vegetables", image: "" },
        { name: "Ice Cream & Kulfi", image: "" },
      ],
    },
    {
      name: "Bakery & Confectionery",
      image: "",
      subcat: [
        { name: "Bread & Buns", image: "" },
        { name: "Cakes & Muffins", image: "" },
        { name: "Cookies & Biscuits", image: "" },
        { name: "Rusk & Namkeen", image: "" },
      ],
    },
  ],
  Glasses: [
    {
      name: "Sunglasses",
      image: "",
      subcat: [
        { name: "Aviator Sunglasses", image: "" },
        { name: "Wayfarer Sunglasses", image: "" },
        { name: "Round Sunglasses", image: "" },
        { name: "Sport Sunglasses", image: "" },
        { name: "Mirror Lens Sunglasses", image: "" },
        { name: "Polarized Sunglasses", image: "" },
      ],
    },
    {
      name: "Spectacles / Eyeglasses",
      image: "",
      subcat: [
        { name: "Full Rim Frames", image: "" },
        { name: "Half Rim Frames", image: "" },
        { name: "Rimless Frames", image: "" },
        { name: "Round Frames", image: "" },
        { name: "Square Frames", image: "" },
        { name: "Metal Frames", image: "" },
        { name: "Plastic Frames", image: "" },
      ],
    },
    {
      name: "Reading & Computer Glasses",
      image: "",
      subcat: [
        { name: "Reading Glasses", image: "" },
        { name: "Blue Light Blocking Glasses", image: "" },
        { name: "Computer / Laptop Glasses", image: "" },
        { name: "Anti-Glare Glasses", image: "" },
      ],
    },
    {
      name: "Kids Glasses",
      image: "",
      subcat: [
        { name: "Kids Sunglasses", image: "" },
        { name: "Kids Spectacles", image: "" },
        { name: "Kids Sports Glasses", image: "" },
      ],
    },
    {
      name: "Sports & Safety Glasses",
      image: "",
      subcat: [
        { name: "Cycling Glasses", image: "" },
        { name: "Swimming Goggles", image: "" },
        { name: "Ski / Snow Glasses", image: "" },
        { name: "Protective / Safety Glasses", image: "" },
      ],
    },
    {
      name: "Fashion & Designer Glasses",
      image: "",
      subcat: [
        { name: "Trendy Sunglasses", image: "" },
        { name: "Retro / Vintage Glasses", image: "" },
        { name: "Celebrity Style Glasses", image: "" },
      ],
    },
    {
      name: "Accessories & Care",
      image: "",
      subcat: [
        { name: "Glass Cases / Pouches", image: "" },
        { name: "Cleaning Cloths & Sprays", image: "" },
        { name: "Replacement Lenses", image: "" },
        { name: "Chains & Straps", image: "" },
      ],
    },
  ],
  Others: [
    {
      name: "Option name",
      image: "",
      subcat: [{ name: "Option value", image: "" }],
    },
  ],
};

export const socialPlatforms = {
  Facebook: { icon: <FaFacebook />, color: "#1877F2" },
  Twitter: { icon: <FaTwitter />, color: "#1DA1F2" },
  Instagram: { icon: <FaInstagram />, color: "#E4405F" },
  LinkedIn: { icon: <FaLinkedin />, color: "#0A66C2" },
  GitHub: { icon: <FaGithub />, color: "#181717" },
  YouTube: { icon: <FaYoutube />, color: "#FF0000" },
  Pinterest: { icon: <FaPinterest />, color: "#E60023" },
  Reddit: { icon: <FaReddit />, color: "#FF4500" },
  TikTok: { icon: <FaTiktok />, color: "#010101" },
  Snapchat: { icon: <FaSnapchat />, color: "#FFFC00" },
  WhatsApp: { icon: <FaWhatsapp />, color: "#25D366" },
  Telegram: { icon: <FaTelegram />, color: "#0088CC" },
  Discord: { icon: <FaDiscord />, color: "#5865F2" },
  Twitch: { icon: <FaTwitch />, color: "#9146FF" },
};

export const testimage = "/testimage.png";
